name: Build and Deploy Multi-Arch Image

on: [push]

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Get the version
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
          VERSION=latest
        fi
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Login ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PASSWORD }}

    - name: Build and push docker images
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        labels: |-
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
        push: true
        platforms: linux/amd64,linux/arm64
        build-args: |
          GOLANG_VERSION=1.17-buster
        tags: |-
          ghcr.io/${{ github.repository_owner }}/multi-arch-build/app-2:${{ steps.get_version.outputs.VERSION }}