name: Create a local manifest list for annotating and pushing to a registry

on: [push]

jobs:
  combine-multi-arch:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Login ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PASSWORD }}

    - name: Build and push docker images
      run: |
        export BUILDX_NO_DEFAULT_ATTESTATIONS=1
        make multi-arch-builder
        make publish